# use the shared YaST defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

Metrics/AbcSize:
  Max: 128

Metrics/BlockLength:
  Max: 591
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockNesting:
  Max: 6

Metrics/ClassLength:
  Max: 650

Metrics/CyclomaticComplexity:
  Max: 34

Metrics/MethodLength:
  Max: 315

Metrics/ModuleLength:
  Max: 760

Metrics/PerceivedComplexity:
  Max: 40

Naming/FileName:
  Exclude:
    - 'src/modules/Security.rb'
    - 'test/SCRStub.rb'

# Do not break API
Naming/MethodName:
  Exclude:
    - 'src/clients/security.rb'
    - 'src/include/security/complex.rb'
    - 'src/include/security/dialogs.rb'
    - 'src/include/security/routines.rb'
    - 'src/include/security/users.rb'
    - 'src/include/security/wizards.rb'
    - 'src/modules/Security.rb'
    - 'test/levels_test.rb'

# Offense count: 9
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/MethodParameterName:
  Exclude:
    - 'src/include/security/routines.rb'
    - 'src/modules/Security.rb'

# Offense count: 29
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'src/include/security/complex.rb'
    - 'src/include/security/dialogs.rb'
    - 'src/include/security/helps.rb'
    - 'src/include/security/levels.rb'
    - 'src/include/security/routines.rb'
    - 'src/include/security/widgets.rb'
    - 'src/modules/Security.rb'

# TODO: if someone has too much spare time, feel free to enable it
Style/Documentation:
  Enabled: false

# Frozen strings are too dangerous to switch now
Style/FrozenStringLiteralComment:
  Enabled: false
